model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: val_l2_band
  mode: min
  save_top_k: 1
  save_last: false
  filename: best

kf_visualizer:
  _target_: src.callbacks.kf_visualizer.KFVisualizerCallback
  log_every_n_epochs: 50
