import torch
import torch.nn.functional as F
from torch import Tensor
from torch.utils.checkpoint import checkpoint


class PeriodicConv3d(torch.nn.Module):
    """Conv3d with per-axis padding matched to Kolmogorov-flow boundary conditions.

    Data is generated by a pseudo-spectral solver on a 2π×2π torus (periodic in
    x,y) and is a forward trajectory in t (non-periodic). So we pad circular on
    the two spatial axes and zero on the temporal axis, then convolve with no
    further padding.

    Input/output: (B, C_in, S, S, T) -> (B, C_out, S, S, T) for odd kernel size.
    """

    def __init__(self, in_channels: int, out_channels: int, kernel_size: int = 3):
        super().__init__()
        assert kernel_size % 2 == 1, "kernel_size must be odd to preserve spatial dims"
        self.pad = kernel_size // 2
        self.conv = torch.nn.Conv3d(in_channels, out_channels, kernel_size, padding=0)

    def forward(self, x: Tensor) -> Tensor:
        p = self.pad
        # F.pad order is last-dim-first: (t_lo, t_hi, y_lo, y_hi, x_lo, x_hi)
        x = F.pad(x, (0, 0, p, p, p, p), mode="circular")      # x, y periodic
        x = F.pad(x, (p, p, 0, 0, 0, 0), mode="constant")      # t zero-padded
        return self.conv(x)


def _group_norm(channels: int) -> torch.nn.GroupNorm:
    """GroupNorm with 8 groups when divisible, else 1 (LayerNorm-like). B=1-safe."""
    groups = 8 if channels % 8 == 0 else 1
    return torch.nn.GroupNorm(groups, channels)


class DoubleConv(torch.nn.Module):
    """Two periodic convs, each followed by GroupNorm + SiLU. Preserves (S, S, T).

    (B, in_channels, S, S, T) -> (B, out_channels, S, S, T)

    If grad_checkpoint is set, activations are discarded in the forward pass and
    recomputed during backward (memory↓, ~25% compute↑). Only active in training.
    """

    def __init__(self, in_channels: int, out_channels: int, grad_checkpoint: bool = False):
        super().__init__()
        self.grad_checkpoint = grad_checkpoint
        self.block = torch.nn.Sequential(
            PeriodicConv3d(in_channels, out_channels),
            _group_norm(out_channels),
            torch.nn.SiLU(),
            PeriodicConv3d(out_channels, out_channels),
            _group_norm(out_channels),
            torch.nn.SiLU(),
        )

    def forward(self, x: Tensor) -> Tensor:
        if self.grad_checkpoint and self.training:
            return checkpoint(self.block, x, use_reentrant=False)
        return self.block(x)


class DownBlock(torch.nn.Module):
    """Anisotropic downsample then DoubleConv. Halves x,y; leaves t unchanged.

    (B, in_channels, S, S, T) -> (B, out_channels, S/2, S/2, T)
    """

    def __init__(self, in_channels: int, out_channels: int, grad_checkpoint: bool = False):
        super().__init__()
        self.pool = torch.nn.MaxPool3d(kernel_size=(2, 2, 1), stride=(2, 2, 1))
        self.conv = DoubleConv(in_channels, out_channels, grad_checkpoint)

    def forward(self, x: Tensor) -> Tensor:
        return self.conv(self.pool(x))


class UpBlock(torch.nn.Module):
    """Anisotropic upsample, concat the encoder skip, then DoubleConv.

    Doubles x,y (trilinear, t scale 1); concatenates the skip on the channel
    axis, so DoubleConv input width is up_channels + skip_channels.

    x:    (B, in_channels,   S/2, S/2, T)
    skip: (B, skip_channels, S,   S,   T)
    out:  (B, out_channels,  S,   S,   T)
    """

    def __init__(self, in_channels: int, skip_channels: int, out_channels: int,
                 grad_checkpoint: bool = False):
        super().__init__()
        self.conv = DoubleConv(in_channels + skip_channels, out_channels, grad_checkpoint)

    def forward(self, x: Tensor, skip: Tensor) -> Tensor:
        x = F.interpolate(x, size=skip.shape[2:], mode="trilinear", align_corners=False)
        return self.conv(torch.cat([x, skip], dim=1))


class UNet3D(torch.nn.Module):
    """3D UNet for Kolmogorov flow with anisotropic (x,y only) down/upsampling.

    Input/output contract (channels-first, matching kf_forward):
        (B, in_channels, S, S, T) -> (B, out_channels, S, S, T)

    Encoder widths are [base * 2**i for i in range(depth+1)]; e.g. base=64,
    depth=3 -> [64, 128, 256, 512]. The deepest is the bottleneck (no skip).
    The temporal axis is never down/upsampled; spatial axes halve per level, so
    S must be divisible by 2**depth.
    """

    def __init__(self, in_channels: int = 4, out_channels: int = 1,
                 base_channels: int = 64, depth: int = 3, grad_checkpoint: bool = False):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.base_channels = base_channels
        self.depth = depth
        self.grad_checkpoint = grad_checkpoint

        ch = [base_channels * 2 ** i for i in range(depth + 1)]
        self.stem = DoubleConv(in_channels, ch[0], grad_checkpoint)
        self.downs = torch.nn.ModuleList(
            DownBlock(ch[i - 1], ch[i], grad_checkpoint) for i in range(1, depth + 1)
        )
        self.ups = torch.nn.ModuleList(
            UpBlock(ch[i], ch[i - 1], ch[i - 1], grad_checkpoint) for i in range(depth, 0, -1)
        )
        self.head = torch.nn.Conv3d(ch[0], out_channels, kernel_size=1)

    def forward(self, x: Tensor) -> Tensor:
        h = self.stem(x)
        skips = [h]
        for i, down in enumerate(self.downs):
            h = down(h)
            if i < self.depth - 1:          # keep every level except the bottleneck
                skips.append(h)
        for up in self.ups:
            h = up(h, skips.pop())
        return self.head(h)
