import torch
import torch.nn.functional as F
from torch import Tensor
from torch.utils.checkpoint import checkpoint


class PeriodicConv3d(torch.nn.Module):
    """Conv3d with per-axis padding matched to Kolmogorov-flow boundary conditions.

    Data is generated by a pseudo-spectral solver on a 2π×2π torus (periodic in
    x,y) and is a forward trajectory in t (non-periodic). So we pad circular on
    the two spatial axes and zero on the temporal axis, then convolve with no
    further padding.

    Input/output: (B, C_in, S, S, T) -> (B, C_out, S, S, T) for odd kernel size.
    """

    def __init__(self, in_channels: int, out_channels: int, kernel_size: int = 3):
        super().__init__()
        assert kernel_size % 2 == 1, "kernel_size must be odd to preserve spatial dims"
        self.pad = kernel_size // 2
        self.conv = torch.nn.Conv3d(in_channels, out_channels, kernel_size, padding=0)

    def forward(self, x: Tensor) -> Tensor:
        p = self.pad
        # F.pad order is last-dim-first: (t_lo, t_hi, y_lo, y_hi, x_lo, x_hi)
        x = F.pad(x, (0, 0, p, p, p, p), mode="circular")      # x, y periodic
        x = F.pad(x, (p, p, 0, 0, 0, 0), mode="constant")      # t zero-padded
        return self.conv(x)


class TemporalSpectralMixer(torch.nn.Module):
    """FNO-style global coupling along t: rfft, scale the lowest `modes` temporal
    Fourier modes per channel, irfft. Residual with zero-init weights → starts as
    identity. (B,C,H,W,T) -> (B,C,H,W,T). T-agnostic (modes capped at T//2+1).
    FFT is forced to fp32 (fp16 rfft is lossy/overflow-prone under AMP).
    """

    def __init__(self, channels: int, modes: int = 16):
        super().__init__()
        self.modes = modes
        # Real storage (C, modes, 2) -> view_as_complex in forward. A complex
        # nn.Parameter breaks AMP: the GradScaler cannot unscale ComplexFloat grads
        # ("_amp_foreach_non_finite_check_and_unscale_ not implemented for ComplexFloat").
        self.weight = torch.nn.Parameter(torch.zeros(channels, modes, 2))

    def forward(self, x: Tensor) -> Tensor:
        T = x.shape[-1]
        m = min(self.modes, T // 2 + 1)
        with torch.autocast(device_type=x.device.type, enabled=False):
            xf = torch.fft.rfft(x.float(), dim=-1)            # (B,C,H,W,T//2+1) complex
            out = torch.zeros_like(xf)
            w = torch.view_as_complex(self.weight[:, :m].contiguous())  # (C, m) complex
            out[..., :m] = xf[..., :m] * w.view(1, -1, 1, 1, m)
            mixed = torch.fft.irfft(out, n=T, dim=-1)          # (B,C,H,W,T) real fp32
        return x + mixed.to(x.dtype)


class TemporalConvMixer(torch.nn.Module):
    """Large-kernel depthwise conv along t (zero-pad, non-periodic). Residual with
    zero-init → starts as identity. Near-global temporal receptive field in one
    layer. (B,C,H,W,T) -> (B,C,H,W,T). T-agnostic.
    """

    def __init__(self, channels: int, kernel: int = 31):
        super().__init__()
        assert kernel % 2 == 1, "temporal conv kernel must be odd"
        self.conv = torch.nn.Conv3d(channels, channels, (1, 1, kernel),
                                    padding=(0, 0, kernel // 2), groups=channels)
        torch.nn.init.zeros_(self.conv.weight)
        torch.nn.init.zeros_(self.conv.bias)

    def forward(self, x: Tensor) -> Tensor:
        return x + self.conv(x)


class TemporalAttnMixer(torch.nn.Module):
    """Multi-head self-attention over the time axis at the bottleneck, with each
    (batch, spatial) position as an independent sequence of T tokens. Residual with
    zero-init output projection → starts as identity. (B,C,H,W,T) -> (B,C,H,W,T).
    T-agnostic.
    """

    def __init__(self, channels: int, heads: int = 4):
        super().__init__()
        self.attn = torch.nn.MultiheadAttention(channels, heads, batch_first=True)
        torch.nn.init.zeros_(self.attn.out_proj.weight)
        torch.nn.init.zeros_(self.attn.out_proj.bias)

    def forward(self, x: Tensor) -> Tensor:
        B, C, H, W, T = x.shape
        seq = x.permute(0, 2, 3, 4, 1).reshape(B * H * W, T, C)   # (B*H*W, T, C)
        # fp16 attention softmax overflows -> NaN; force fp32 under AMP (cf. PDE loss).
        with torch.autocast(device_type=x.device.type, enabled=False):
            out, _ = self.attn(seq.float(), seq.float(), seq.float())
        out = out.reshape(B, H, W, T, C).permute(0, 4, 1, 2, 3)
        return x + out.to(x.dtype)


class SpatialSpectralMixer(torch.nn.Module):
    """FNO-style spectral conv over (x,y) at the bottleneck WITH channel mixing,
    made cheap by a 1x1 channel bottleneck (channels -> hidden -> channels). Keeps
    the lowest `modes` spatial Fourier modes per axis; for each kept mode all
    `hidden` channels mix (the FNO ingredient a plain conv lacks). Acts per (batch,
    t). Zero-init up-projection -> identity at start (baseline-safe); the spectral
    weights are NOT zero, so they get a real gradient once `up` moves off zero.
    FFT forced fp32 under AMP; complex weights stored real (view_as_complex) so the
    GradScaler can unscale grads. (B,C,H,W,T) -> (B,C,H,W,T).
    """

    def __init__(self, channels: int, modes: int = 8, hidden: int = 64):
        super().__init__()
        h = min(hidden, channels)
        self.modes = modes
        self.down = torch.nn.Conv3d(channels, h, 1)
        self.up = torch.nn.Conv3d(h, channels, 1)
        scale = 1.0 / (h * h)
        self.w_lo = torch.nn.Parameter(scale * torch.randn(h, h, modes, modes, 2))
        self.w_hi = torch.nn.Parameter(scale * torch.randn(h, h, modes, modes, 2))
        torch.nn.init.zeros_(self.up.weight)
        torch.nn.init.zeros_(self.up.bias)

    @staticmethod
    def _mix(xf: Tensor, w: Tensor) -> Tensor:
        wc = torch.view_as_complex(w.contiguous())
        return torch.einsum("bihwt,iohw->bohwt", xf, wc)

    def forward(self, x: Tensor) -> Tensor:
        H, W = x.shape[2], x.shape[3]
        z = self.down(x)
        m1 = min(self.modes, H // 2)
        m2 = min(self.modes, W // 2 + 1)
        with torch.autocast(device_type=x.device.type, enabled=False):
            zf = torch.fft.rfft2(z.float(), dim=(2, 3))        # (B,h,H,W//2+1,T)
            out = torch.zeros_like(zf)
            if m1 > 0:
                out[:, :, :m1, :m2] = self._mix(zf[:, :, :m1, :m2], self.w_lo[:, :, :m1, :m2])
                out[:, :, -m1:, :m2] = self._mix(zf[:, :, -m1:, :m2], self.w_hi[:, :, :m1, :m2])
            mixed = torch.fft.irfft2(out, s=(H, W), dim=(2, 3))  # (B,h,H,W,T) real
        return x + self.up(mixed.to(x.dtype))


def build_temporal_mixer(kind: str, channels: int, *, modes: int = 16,
                         kernel: int = 31, heads: int = 4, hidden: int = 64) -> torch.nn.Module:
    """Construct a bottleneck mixer. 'none' -> Identity (baseline). 'spatial' is the
    channel-mixing FNO spectral block over x,y; the rest act on the t axis."""
    kind = str(kind).lower()
    if kind == "none":
        return torch.nn.Identity()
    if kind == "spectral":
        return TemporalSpectralMixer(channels, modes)
    if kind == "conv":
        return TemporalConvMixer(channels, kernel)
    if kind == "attn":
        return TemporalAttnMixer(channels, heads)
    if kind == "spatial":
        return SpatialSpectralMixer(channels, modes=modes, hidden=hidden)
    raise ValueError(
        f"unknown temporal_mixer '{kind}'; expected none|spectral|conv|attn|spatial")


def _group_norm(channels: int) -> torch.nn.GroupNorm:
    """GroupNorm with 8 groups when divisible, else 1 (LayerNorm-like). B=1-safe."""
    groups = 8 if channels % 8 == 0 else 1
    return torch.nn.GroupNorm(groups, channels)


class DoubleConv(torch.nn.Module):
    """Two periodic convs, each followed by GroupNorm + SiLU. Preserves (S, S, T).

    (B, in_channels, S, S, T) -> (B, out_channels, S, S, T)

    If grad_checkpoint is set, activations are discarded in the forward pass and
    recomputed during backward (memory↓, ~25% compute↑). Only active in training.
    """

    def __init__(self, in_channels: int, out_channels: int, grad_checkpoint: bool = False):
        super().__init__()
        self.grad_checkpoint = grad_checkpoint
        self.block = torch.nn.Sequential(
            PeriodicConv3d(in_channels, out_channels),
            _group_norm(out_channels),
            torch.nn.SiLU(),
            PeriodicConv3d(out_channels, out_channels),
            _group_norm(out_channels),
            torch.nn.SiLU(),
        )

    def forward(self, x: Tensor) -> Tensor:
        if self.grad_checkpoint and self.training:
            return checkpoint(self.block, x, use_reentrant=False)
        return self.block(x)


class DownBlock(torch.nn.Module):
    """Anisotropic downsample then DoubleConv. Halves x,y; leaves t unchanged.

    (B, in_channels, S, S, T) -> (B, out_channels, S/2, S/2, T)
    """

    def __init__(self, in_channels: int, out_channels: int, grad_checkpoint: bool = False):
        super().__init__()
        self.pool = torch.nn.MaxPool3d(kernel_size=(2, 2, 1), stride=(2, 2, 1))
        self.conv = DoubleConv(in_channels, out_channels, grad_checkpoint)

    def forward(self, x: Tensor) -> Tensor:
        return self.conv(self.pool(x))


class UpBlock(torch.nn.Module):
    """Anisotropic upsample, concat the encoder skip, then DoubleConv.

    Doubles x,y (trilinear, t scale 1); concatenates the skip on the channel
    axis, so DoubleConv input width is up_channels + skip_channels.

    x:    (B, in_channels,   S/2, S/2, T)
    skip: (B, skip_channels, S,   S,   T)
    out:  (B, out_channels,  S,   S,   T)
    """

    def __init__(self, in_channels: int, skip_channels: int, out_channels: int,
                 grad_checkpoint: bool = False):
        super().__init__()
        self.conv = DoubleConv(in_channels + skip_channels, out_channels, grad_checkpoint)

    def forward(self, x: Tensor, skip: Tensor) -> Tensor:
        x = F.interpolate(x, size=skip.shape[2:], mode="trilinear", align_corners=False)
        return self.conv(torch.cat([x, skip], dim=1))


class UNet3D(torch.nn.Module):
    """3D UNet for Kolmogorov flow with anisotropic (x,y only) down/upsampling.

    Input/output contract (channels-first, matching kf_forward):
        (B, in_channels, S, S, T) -> (B, out_channels, S, S, T)

    Encoder widths are [base * 2**i for i in range(depth+1)]; e.g. base=64,
    depth=3 -> [64, 128, 256, 512]. The deepest is the bottleneck (no skip).
    The temporal axis is never down/upsampled; spatial axes halve per level, so
    S must be divisible by 2**depth.
    """

    def __init__(self, in_channels: int = 4, out_channels: int = 1,
                 base_channels: int = 64, depth: int = 3, grad_checkpoint: bool = False,
                 temporal_mixer: str = "none", temporal_mixer_modes: int = 16,
                 temporal_mixer_kernel: int = 31, temporal_mixer_heads: int = 4,
                 spatial_mixer_hidden: int = 64):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.base_channels = base_channels
        self.depth = depth
        self.grad_checkpoint = grad_checkpoint
        self.temporal_mixer_kind = str(temporal_mixer).lower()

        ch = [base_channels * 2 ** i for i in range(depth + 1)]
        self.stem = DoubleConv(in_channels, ch[0], grad_checkpoint)
        self.downs = torch.nn.ModuleList(
            DownBlock(ch[i - 1], ch[i], grad_checkpoint) for i in range(1, depth + 1)
        )
        self.temporal_mixer = build_temporal_mixer(
            temporal_mixer, ch[depth], modes=temporal_mixer_modes,
            kernel=temporal_mixer_kernel, heads=temporal_mixer_heads,
            hidden=spatial_mixer_hidden,
        )
        self.ups = torch.nn.ModuleList(
            UpBlock(ch[i], ch[i - 1], ch[i - 1], grad_checkpoint) for i in range(depth, 0, -1)
        )
        self.head = torch.nn.Conv3d(ch[0], out_channels, kernel_size=1)

    def forward(self, x: Tensor) -> Tensor:
        h = self.stem(x)
        skips = [h]
        for i, down in enumerate(self.downs):
            h = down(h)
            if i < self.depth - 1:          # keep every level except the bottleneck
                skips.append(h)
        h = self.temporal_mixer(h)          # global coupling along t (Identity if 'none')
        for up in self.ups:
            h = up(h, skips.pop())
        return self.head(h)
